version: '2.2'
services:
  frontend:
    build: ./frontend
    ports:
      - "${REST_PORT:-8081}:80"
    volumes:
      - "./frontend/public/:/app/public/:ro"
      - "./frontend/src/:/app/src/:ro"
    depends_on:
      - rest
  rest:
    build: ./rest
    ports:
      - "${REST_PORT:-8080}:80"
    volumes:
      - "./rest/src/:/app/src/:ro"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.1
    restart: always
    ports:
    - "27017:27017"
