version: '3'
services:
  rest:
    build: ./rest
    ports:
      - "${REST_PORT:-8080}:80"
    volumes:
      - "./rest/src/:/app/src/:ro"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.1
    restart: always
    ports:
    - "27017:27017"
